add ansible install

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,9 +2,17 @@
 
 user_name=$(whoami)
 env_home="/home/$user_name/.ansible-venv"
+env_python="$env_home/bin/python"
+env_pip="$env_home/bin/pip"
+env_ansible="$env_home/bin/ansible"
+
+if ! command -v python &> /dev/null; then
+    echo "Python is required"
+    exit 1
+fi
 
 echo "Создаем виртуальную среду"
-
 python -m venv $env_home
 
-$env_home/bin/pip install ansible
+echo "Устанавливаем Ansible"
+$env_pip install ansible
